### PR TITLE
[MSHARED-1024] Replace deprecated code

### PR DESCRIPTION
**Pull request by michael-o**
This closes #2

### CODE REVIEW

**Comment by basil** [comment]
FYI this breaks binary compatibility with https://github.com/kohsuke/maven-jellydoc-plugin and https://github.com/jenkinsci/maven-stapler-plugin:

https://github.com/jenkins-infra/helpdesk/issues/3049#issuecomment-1186294149

But I suppose we are long past the point where such binary compatibility could reasonably be expected. I will try to update the consumers.

**Comment by michael-o** [comment]
> FYI this breaks binary compatibility with https://github.com/kohsuke/maven-jellydoc-plugin and https://github.com/jenkinsci/maven-stapler-plugin:
> 
> [jenkins-infra/helpdesk#3049 (comment)](https://github.com/jenkins-infra/helpdesk/issues/3049#issuecomment-1186294149)
> 
> But I suppose we are long past the point where such binary compatibility could reasonably be expected. I will try to update the consumers.

That's true, but is a major and we have to remove at some point. Those methods were deprecated for a long time.

**Comment by basil** [comment]
Was this breaking change documented in any release notes?

**Comment by michael-o** [comment]
I need to revert my previous statement because I had another release in memory. Yes, this change was partially wrong and I haven't anticipated people still using 10 years old deprecated interfaces. It should have happened only in a new major version. Although I am still surprised that code even being deprecated and the IDE tells you the successor is still not changed. BTW, same happened with Asciidoctor Maven Plugin. Sorry for the inconvenience.

**Comment by michael-o** [comment]
Would you prefer a patch release with a revert? This code will go away in 4.0.0 anyway.

**Comment by basil** [comment]
Thanks Michael, that would definitely be appreciated as otherwise I need to go obtaining write access to two ancient Maven plugins to modernize them and perform new releases, which I would rather not rush to do.

**Comment by michael-o** [comment]
> Thanks Michael, that would definitely be appreciated as otherwise I need to go obtaining write access to two ancient Maven plugins to modernize them and perform new releases, which I would rather not rush to do.

That would only be an interims solution because with Maven Site Plugin 4 they will fail anyway. Please file an issue with MSHARED and link this conversation to it.

**Comment by jira-importer** [comment]
Resolve #29

**Pull request merged**
